### ISSUE TITLE
Data format

### ISSUE THREAD

**Issue by aminrabinia** [gasparramoa/DoorDetect-Class-Dataset#1]
Hi, 

Great job with building the dataset. I was wondering what the dataset format is. CVAT supports many different formats. Which one did you use for this dataset?

Thanks
Amin

**Comment by gasparramoa** [comment]
Hello Amin,

Thank you for your interest in this project and your feedback! 😀

The CVAT format that I used at the time was the _Mask.zip_ format but, from what I look up into the new documentation no longer exists. The annotations are grayscale, and for the background, the value is 2 and, for the foreground (door frame), the value is 1. 

I would probably use the _PASCAL VOC Segmentation mask_ format: [CVAT Documentation here](https://openvinotoolkit.github.io/cvat/docs/manual/advanced/formats/format-voc/)
You will need to create a _labelmap.txt_ file with the following:

<pre><code># label:color_rgb:parts:actions   (this is a comment)
door:1,1,1::
background:2,2,2::
</code></pre>

And then, you can import via CVAT and export to your required format. 

I would also suggest you take a look at the newest version of this dataset here: [DeepDoors2](https://github.com/gasparramoa/DeepDoors2)

Thank you,
Gaspar Ramôa

**Comment by aminrabinia** [comment]
Oh this is great. Thank you very much!!!

**Comment by gasparramoa** [comment]
You are welcome!! Glad I could help.
